import { Inter } from "next/font/google";
import "./globals.css";
import ReactProvider from "../store/redux-provider";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Manitejarao.Gurenka",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black`}>
        <ReactProvider>
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </ReactProvider>
      </body>
    </html>
  );
}
